name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install
        run: npm install --dev
      - name: Compile
        run: npm run compile
  test:
    needs: build
    runs-on: ubuntu-latest
      steps:
      - run: ls
      - run: pwd
      - name: Run tests
        run: npm run jest
